name: Scheduler Timing Test

on:
  schedule:
    - cron:  '*/30 * * * *' # all day of the week all hours at the 7th and the 37th minute
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install dateutil
    - name: Run main script
      run: python main.py
    - name: Pull Remote Changes again
      run: git pull
    - name: Print current time
      run: echo $(date +'%Y-%m-%dT%H:%M:%S')
    - name: Push Remote Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: scheduled testrun
